# Generated by Django 6.1.1 on 2026-09-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=10)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
